use_frameworks!
source 'https://github.com/zhengya123/ZYModule.git'
platform :ios, '8.0'

target 'ZYCategoryModule_Example' do
  pod 'ZYCategoryModule', :path => '../'
  pod 'ZYImageModule'
  
  target 'ZYCategoryModule_Tests' do
    inherit! :search_paths

    
  end
end
